# Generated by Django 4.2.2 on 2023-06-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0003_habitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
