# Generated by Django 4.2.2 on 2023-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0006_rename_date_habitrecord_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
