# Generated by Django 4.2.2 on 2023-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0008_alter_habitrecord_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitrecord',
            name='number',
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
