# Generated by Django 4.2.2 on 2023-06-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0009_remove_habitrecord_number_habitrecord_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitrecord',
            old_name='name',
            new_name='achieved',
        ),
    ]
