# Generated by Django 4.2.2 on 2023-06-06 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0010_rename_name_habitrecord_achieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitrecord',
            name='created',
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='record_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
