# Generated by Django 4.2.2 on 2023-06-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0013_alter_habitrecord_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='habit',
        ),
    ]
