# Generated by Django 4.2.2 on 2023-06-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0023_alter_habitrecord_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habit'),
            preserve_default=False,
        ),
    ]
