# Generated by Django 4.2.2 on 2023-06-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0024_remove_habit_user_alter_habitrecord_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HabitRecords', to='habitTracker.habit'),
        ),
    ]
