# Generated by Django 4.2.2 on 2023-06-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0026_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='achieved',
            field=models.IntegerField(default=0),
        ),
    ]
