# Generated by Django 4.2.2 on 2023-06-08 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0030_alter_habitrecord_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='habitrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'record_date'), name='unique_constr'),
        ),
    ]
