# Generated by Django 4.2.2 on 2023-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0031_alter_habitrecord_record_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitrecord',
            options={'ordering': ['record_date']},
        ),
    ]
